package id.co.ogya.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2023-03-06T13:35:49.802+07:00
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "http://soap.ogya.co.id/", name = "TransferService")
@XmlSeeAlso({ObjectFactory.class})
public interface TransferService {

    @WebMethod
    @Action(input = "http://soap.ogya.co.id/TransferService/transferDanaRequest", output = "http://soap.ogya.co.id/TransferService/transferDanaResponse")
    @RequestWrapper(localName = "transferDana", targetNamespace = "http://soap.ogya.co.id/", className = "id.co.ogya.soap.TransferDana")
    @ResponseWrapper(localName = "transferDanaResponse", targetNamespace = "http://soap.ogya.co.id/", className = "id.co.ogya.soap.TransferDanaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public id.co.ogya.soap.TransferResponse transferDana(

        @WebParam(name = "arg0", targetNamespace = "")
        id.co.ogya.soap.TransferRequest arg0
    );
}
